AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamic-data-retrival

  Sample SAM Template for dynamic-data-retrival
  
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

        DailyRetrain:
          Type: Schedule
          Properties:
            Schedule: cron(0 3 * * ? *)
            Name: DailyRetrainEvent
            Description: "Daily model retraining at 3 AM"
            Enabled: true